namespace AeroCasilleroProyecto
{
    partial class CasilleroForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            panelHeader = new Panel();
            lblTitulo = new Label();
            lblSubtitulo = new Label();
            panelForm = new Panel();
            lblNumero = new Label();
            txtNumero = new TextBox();
            lblUbicacion = new Label();
            txtUbicacion = new TextBox();
            lblTamano = new Label();
            cboTamano = new ComboBox();
            lblEstado = new Label();
            cboEstado = new ComboBox();
            btnGuardar = new Button();
            btnLimpiar = new Button();
            panelListado = new Panel();
            lblCantidad = new Label();
            dgvCasilleros = new DataGridView();
            panelHeader.SuspendLayout();
            panelForm.SuspendLayout();
            panelListado.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvCasilleros).BeginInit();
            SuspendLayout();
            panelHeader.BackColor = Color.FromArgb(33, 48, 74);
            panelHeader.Controls.Add(lblTitulo);
            panelHeader.Controls.Add(lblSubtitulo);
            panelHeader.Dock = DockStyle.Top;
            panelHeader.Location = new Point(0, 0);
            panelHeader.Name = "panelHeader";
            panelHeader.Size = new Size(1184, 120);
            panelHeader.TabIndex = 0;
            lblTitulo.AutoSize = true;
            lblTitulo.Font = new Font("Segoe UI", 22F, FontStyle.Bold, GraphicsUnit.Point);
            lblTitulo.ForeColor = Color.White;
            lblTitulo.Location = new Point(32, 20);
            lblTitulo.Name = "lblTitulo";
            lblTitulo.Size = new Size(386, 41);
            lblTitulo.TabIndex = 0;
            lblTitulo.Text = "Registro de Casilleros";
            lblSubtitulo.AutoSize = true;
            lblSubtitulo.Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
            lblSubtitulo.ForeColor = Color.Gainsboro;
            lblSubtitulo.Location = new Point(35, 68);
            lblSubtitulo.Name = "lblSubtitulo";
            lblSubtitulo.Size = new Size(371, 19);
            lblSubtitulo.TabIndex = 1;
            lblSubtitulo.Text = "Pantalla de prueba para administrar casilleros del sistema";
            panelForm.BackColor = Color.FromArgb(245, 247, 250);
            panelForm.Controls.Add(lblNumero);
            panelForm.Controls.Add(txtNumero);
            panelForm.Controls.Add(lblUbicacion);
            panelForm.Controls.Add(txtUbicacion);
            panelForm.Controls.Add(lblTamano);
            panelForm.Controls.Add(cboTamano);
            panelForm.Controls.Add(lblEstado);
            panelForm.Controls.Add(cboEstado);
            panelForm.Controls.Add(btnGuardar);
            panelForm.Controls.Add(btnLimpiar);
            panelForm.Location = new Point(24, 144);
            panelForm.Name = "panelForm";
            panelForm.Size = new Size(420, 520);
            panelForm.TabIndex = 1;
            lblNumero.AutoSize = true;
            lblNumero.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblNumero.Location = new Point(22, 22);
            lblNumero.Name = "lblNumero";
            lblNumero.Size = new Size(48, 15);
            lblNumero.TabIndex = 0;
            lblNumero.Text = "Número";
            txtNumero.Location = new Point(22, 40);
            txtNumero.Name = "txtNumero";
            txtNumero.Size = new Size(370, 23);
            txtNumero.TabIndex = 1;
            lblUbicacion.AutoSize = true;
            lblUbicacion.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblUbicacion.Location = new Point(22, 76);
            lblUbicacion.Name = "lblUbicacion";
            lblUbicacion.Size = new Size(65, 15);
            lblUbicacion.TabIndex = 2;
            lblUbicacion.Text = "Ubicación";
            txtUbicacion.Location = new Point(22, 94);
            txtUbicacion.Name = "txtUbicacion";
            txtUbicacion.Size = new Size(370, 23);
            txtUbicacion.TabIndex = 3;
            lblTamano.AutoSize = true;
            lblTamano.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblTamano.Location = new Point(22, 130);
            lblTamano.Name = "lblTamano";
            lblTamano.Size = new Size(51, 15);
            lblTamano.TabIndex = 4;
            lblTamano.Text = "Tamaño";
            cboTamano.DropDownStyle = ComboBoxStyle.DropDownList;
            cboTamano.FormattingEnabled = true;
            cboTamano.Items.AddRange(new object[] { "Pequeño", "Mediano", "Grande" });
            cboTamano.Location = new Point(22, 148);
            cboTamano.Name = "cboTamano";
            cboTamano.Size = new Size(370, 23);
            cboTamano.TabIndex = 5;
            lblEstado.AutoSize = true;
            lblEstado.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblEstado.Location = new Point(22, 184);
            lblEstado.Name = "lblEstado";
            lblEstado.Size = new Size(43, 15);
            lblEstado.TabIndex = 6;
            lblEstado.Text = "Estado";
            cboEstado.DropDownStyle = ComboBoxStyle.DropDownList;
            cboEstado.FormattingEnabled = true;
            cboEstado.Items.AddRange(new object[] { "Disponible", "FueraDeServicio" });
            cboEstado.Location = new Point(22, 202);
            cboEstado.Name = "cboEstado";
            cboEstado.Size = new Size(370, 23);
            cboEstado.TabIndex = 7;
            btnGuardar.BackColor = Color.FromArgb(39, 174, 96);
            btnGuardar.FlatStyle = FlatStyle.Flat;
            btnGuardar.ForeColor = Color.White;
            btnGuardar.Location = new Point(22, 270);
            btnGuardar.Name = "btnGuardar";
            btnGuardar.Size = new Size(170, 42);
            btnGuardar.TabIndex = 8;
            btnGuardar.Text = "Guardar casillero";
            btnGuardar.UseVisualStyleBackColor = false;
            btnGuardar.Click += btnGuardar_Click;
            btnLimpiar.BackColor = Color.FromArgb(236, 240, 241);
            btnLimpiar.FlatStyle = FlatStyle.Flat;
            btnLimpiar.ForeColor = Color.FromArgb(44, 62, 80);
            btnLimpiar.Location = new Point(222, 270);
            btnLimpiar.Name = "btnLimpiar";
            btnLimpiar.Size = new Size(170, 42);
            btnLimpiar.TabIndex = 9;
            btnLimpiar.Text = "Limpiar";
            btnLimpiar.UseVisualStyleBackColor = false;
            btnLimpiar.Click += btnLimpiar_Click;
            panelListado.BackColor = Color.White;
            panelListado.Controls.Add(lblCantidad);
            panelListado.Controls.Add(dgvCasilleros);
            panelListado.Location = new Point(468, 144);
            panelListado.Name = "panelListado";
            panelListado.Size = new Size(692, 520);
            panelListado.TabIndex = 2;
            lblCantidad.AutoSize = true;
            lblCantidad.Font = new Font("Segoe UI", 10F, FontStyle.Bold, GraphicsUnit.Point);
            lblCantidad.Location = new Point(18, 18);
            lblCantidad.Name = "lblCantidad";
            lblCantidad.Size = new Size(162, 19);
            lblCantidad.TabIndex = 0;
            lblCantidad.Text = "Casilleros registrados:";
            dgvCasilleros.AllowUserToAddRows = false;
            dgvCasilleros.AllowUserToDeleteRows = false;
            dgvCasilleros.BackgroundColor = Color.White;
            dgvCasilleros.BorderStyle = BorderStyle.None;
            dgvCasilleros.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvCasilleros.Location = new Point(18, 52);
            dgvCasilleros.Name = "dgvCasilleros";
            dgvCasilleros.ReadOnly = true;
            dgvCasilleros.RowHeadersVisible = false;
            dgvCasilleros.RowTemplate.Height = 25;
            dgvCasilleros.Size = new Size(656, 450);
            dgvCasilleros.TabIndex = 1;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(230, 233, 238);
            ClientSize = new Size(1184, 701);
            Controls.Add(panelListado);
            Controls.Add(panelForm);
            Controls.Add(panelHeader);
            Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
            MinimumSize = new Size(1200, 740);
            Name = "CasilleroForm";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Registro de Casilleros";
            panelHeader.ResumeLayout(false);
            panelHeader.PerformLayout();
            panelForm.ResumeLayout(false);
            panelForm.PerformLayout();
            panelListado.ResumeLayout(false);
            panelListado.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvCasilleros).EndInit();
            ResumeLayout(false);
        }

        private Panel panelHeader;
        private Label lblTitulo;
        private Label lblSubtitulo;
        private Panel panelForm;
        private Label lblNumero;
        private TextBox txtNumero;
        private Label lblUbicacion;
        private TextBox txtUbicacion;
        private Label lblTamano;
        private ComboBox cboTamano;
        private Label lblEstado;
        private ComboBox cboEstado;
        private Button btnGuardar;
        private Button btnLimpiar;
        private Panel panelListado;
        private Label lblCantidad;
        private DataGridView dgvCasilleros;
    }
}
