namespace AeroCasilleroProyecto
{
    partial class PaqueteForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            panelHeader = new Panel();
            lblTitulo = new Label();
            lblSubtitulo = new Label();
            panelForm = new Panel();
            lblTracking = new Label();
            txtTracking = new TextBox();
            lblPeso = new Label();
            nudPeso = new NumericUpDown();
            lblAlto = new Label();
            nudAlto = new NumericUpDown();
            lblAncho = new Label();
            nudAncho = new NumericUpDown();
            lblLargo = new Label();
            nudLargo = new NumericUpDown();
            lblTransportista = new Label();
            txtTransportista = new TextBox();
            lblFechaRecepcion = new Label();
            dtpFechaRecepcion = new DateTimePicker();
            lblObservaciones = new Label();
            txtObservaciones = new TextBox();
            lblCliente = new Label();
            txtCliente = new TextBox();
            btnGuardar = new Button();
            btnLimpiar = new Button();
            panelListado = new Panel();
            lblCantidad = new Label();
            dgvPaquetes = new DataGridView();
            panelHeader.SuspendLayout();
            panelForm.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)nudPeso).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudAlto).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudAncho).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudLargo).BeginInit();
            panelListado.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvPaquetes).BeginInit();
            SuspendLayout();
            panelHeader.BackColor = Color.FromArgb(33, 48, 74);
            panelHeader.Controls.Add(lblTitulo);
            panelHeader.Controls.Add(lblSubtitulo);
            panelHeader.Dock = DockStyle.Top;
            panelHeader.Location = new Point(0, 0);
            panelHeader.Name = "panelHeader";
            panelHeader.Size = new Size(1184, 120);
            panelHeader.TabIndex = 0;
            lblTitulo.AutoSize = true;
            lblTitulo.Font = new Font("Segoe UI", 22F, FontStyle.Bold, GraphicsUnit.Point);
            lblTitulo.ForeColor = Color.White;
            lblTitulo.Location = new Point(32, 20);
            lblTitulo.Name = "lblTitulo";
            lblTitulo.Size = new Size(380, 41);
            lblTitulo.TabIndex = 0;
            lblTitulo.Text = "Registro de Paquetes";
            lblSubtitulo.AutoSize = true;
            lblSubtitulo.Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
            lblSubtitulo.ForeColor = Color.Gainsboro;
            lblSubtitulo.Location = new Point(35, 68);
            lblSubtitulo.Name = "lblSubtitulo";
            lblSubtitulo.Size = new Size(386, 19);
            lblSubtitulo.TabIndex = 1;
            lblSubtitulo.Text = "Pantalla de prueba para el flujo de recepción de paquetes";
            panelForm.BackColor = Color.FromArgb(245, 247, 250);
            panelForm.Controls.Add(lblTracking);
            panelForm.Controls.Add(txtTracking);
            panelForm.Controls.Add(lblPeso);
            panelForm.Controls.Add(nudPeso);
            panelForm.Controls.Add(lblAlto);
            panelForm.Controls.Add(nudAlto);
            panelForm.Controls.Add(lblAncho);
            panelForm.Controls.Add(nudAncho);
            panelForm.Controls.Add(lblLargo);
            panelForm.Controls.Add(nudLargo);
            panelForm.Controls.Add(lblTransportista);
            panelForm.Controls.Add(txtTransportista);
            panelForm.Controls.Add(lblFechaRecepcion);
            panelForm.Controls.Add(dtpFechaRecepcion);
            panelForm.Controls.Add(lblObservaciones);
            panelForm.Controls.Add(txtObservaciones);
            panelForm.Controls.Add(lblCliente);
            panelForm.Controls.Add(txtCliente);
            panelForm.Controls.Add(btnGuardar);
            panelForm.Controls.Add(btnLimpiar);
            panelForm.Location = new Point(24, 144);
            panelForm.Name = "panelForm";
            panelForm.Size = new Size(420, 520);
            panelForm.TabIndex = 1;
            lblTracking.AutoSize = true;
            lblTracking.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblTracking.Location = new Point(22, 22);
            lblTracking.Name = "lblTracking";
            lblTracking.Size = new Size(55, 15);
            lblTracking.TabIndex = 0;
            lblTracking.Text = "Tracking";
            txtTracking.Location = new Point(22, 40);
            txtTracking.Name = "txtTracking";
            txtTracking.Size = new Size(370, 23);
            txtTracking.TabIndex = 1;
            lblPeso.AutoSize = true;
            lblPeso.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblPeso.Location = new Point(22, 76);
            lblPeso.Name = "lblPeso";
            lblPeso.Size = new Size(36, 15);
            lblPeso.TabIndex = 2;
            lblPeso.Text = "Peso";
            nudPeso.DecimalPlaces = 2;
            nudPeso.Location = new Point(22, 94);
            nudPeso.Maximum = new decimal(new int[] { 9999, 0, 0, 0 });
            nudPeso.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            nudPeso.Name = "nudPeso";
            nudPeso.Size = new Size(170, 23);
            nudPeso.TabIndex = 3;
            nudPeso.Value = new decimal(new int[] { 1, 0, 0, 0 });
            lblAlto.AutoSize = true;
            lblAlto.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblAlto.Location = new Point(222, 76);
            lblAlto.Name = "lblAlto";
            lblAlto.Size = new Size(33, 15);
            lblAlto.TabIndex = 4;
            lblAlto.Text = "Alto";
            nudAlto.DecimalPlaces = 2;
            nudAlto.Location = new Point(222, 94);
            nudAlto.Maximum = new decimal(new int[] { 9999, 0, 0, 0 });
            nudAlto.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            nudAlto.Name = "nudAlto";
            nudAlto.Size = new Size(170, 23);
            nudAlto.TabIndex = 5;
            nudAlto.Value = new decimal(new int[] { 1, 0, 0, 0 });
            lblAncho.AutoSize = true;
            lblAncho.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblAncho.Location = new Point(22, 130);
            lblAncho.Name = "lblAncho";
            lblAncho.Size = new Size(46, 15);
            lblAncho.TabIndex = 6;
            lblAncho.Text = "Ancho";
            nudAncho.DecimalPlaces = 2;
            nudAncho.Location = new Point(22, 148);
            nudAncho.Maximum = new decimal(new int[] { 9999, 0, 0, 0 });
            nudAncho.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            nudAncho.Name = "nudAncho";
            nudAncho.Size = new Size(170, 23);
            nudAncho.TabIndex = 7;
            nudAncho.Value = new decimal(new int[] { 1, 0, 0, 0 });
            lblLargo.AutoSize = true;
            lblLargo.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblLargo.Location = new Point(222, 130);
            lblLargo.Name = "lblLargo";
            lblLargo.Size = new Size(41, 15);
            lblLargo.TabIndex = 8;
            lblLargo.Text = "Largo";
            nudLargo.DecimalPlaces = 2;
            nudLargo.Location = new Point(222, 148);
            nudLargo.Maximum = new decimal(new int[] { 9999, 0, 0, 0 });
            nudLargo.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            nudLargo.Name = "nudLargo";
            nudLargo.Size = new Size(170, 23);
            nudLargo.TabIndex = 9;
            nudLargo.Value = new decimal(new int[] { 1, 0, 0, 0 });
            lblTransportista.AutoSize = true;
            lblTransportista.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblTransportista.Location = new Point(22, 184);
            lblTransportista.Name = "lblTransportista";
            lblTransportista.Size = new Size(81, 15);
            lblTransportista.TabIndex = 10;
            lblTransportista.Text = "Transportista";
            txtTransportista.Location = new Point(22, 202);
            txtTransportista.Name = "txtTransportista";
            txtTransportista.Size = new Size(370, 23);
            txtTransportista.TabIndex = 11;
            lblFechaRecepcion.AutoSize = true;
            lblFechaRecepcion.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblFechaRecepcion.Location = new Point(22, 238);
            lblFechaRecepcion.Name = "lblFechaRecepcion";
            lblFechaRecepcion.Size = new Size(106, 15);
            lblFechaRecepcion.TabIndex = 12;
            lblFechaRecepcion.Text = "Fecha Recepción";
            dtpFechaRecepcion.Location = new Point(22, 256);
            dtpFechaRecepcion.Name = "dtpFechaRecepcion";
            dtpFechaRecepcion.Size = new Size(370, 23);
            dtpFechaRecepcion.TabIndex = 13;
            lblObservaciones.AutoSize = true;
            lblObservaciones.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblObservaciones.Location = new Point(22, 292);
            lblObservaciones.Name = "lblObservaciones";
            lblObservaciones.Size = new Size(91, 15);
            lblObservaciones.TabIndex = 14;
            lblObservaciones.Text = "Observaciones";
            txtObservaciones.Location = new Point(22, 310);
            txtObservaciones.Name = "txtObservaciones";
            txtObservaciones.Size = new Size(370, 23);
            txtObservaciones.TabIndex = 15;
            lblCliente.AutoSize = true;
            lblCliente.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblCliente.Location = new Point(22, 346);
            lblCliente.Name = "lblCliente";
            lblCliente.Size = new Size(46, 15);
            lblCliente.TabIndex = 16;
            lblCliente.Text = "Cliente";
            txtCliente.Location = new Point(22, 364);
            txtCliente.Name = "txtCliente";
            txtCliente.Size = new Size(370, 23);
            txtCliente.TabIndex = 17;
            btnGuardar.BackColor = Color.FromArgb(39, 174, 96);
            btnGuardar.FlatStyle = FlatStyle.Flat;
            btnGuardar.ForeColor = Color.White;
            btnGuardar.Location = new Point(22, 416);
            btnGuardar.Name = "btnGuardar";
            btnGuardar.Size = new Size(170, 42);
            btnGuardar.TabIndex = 18;
            btnGuardar.Text = "Guardar paquete";
            btnGuardar.UseVisualStyleBackColor = false;
            btnGuardar.Click += btnGuardar_Click;
            btnLimpiar.BackColor = Color.FromArgb(236, 240, 241);
            btnLimpiar.FlatStyle = FlatStyle.Flat;
            btnLimpiar.ForeColor = Color.FromArgb(44, 62, 80);
            btnLimpiar.Location = new Point(222, 416);
            btnLimpiar.Name = "btnLimpiar";
            btnLimpiar.Size = new Size(170, 42);
            btnLimpiar.TabIndex = 19;
            btnLimpiar.Text = "Limpiar";
            btnLimpiar.UseVisualStyleBackColor = false;
            btnLimpiar.Click += btnLimpiar_Click;
            panelListado.BackColor = Color.White;
            panelListado.Controls.Add(lblCantidad);
            panelListado.Controls.Add(dgvPaquetes);
            panelListado.Location = new Point(468, 144);
            panelListado.Name = "panelListado";
            panelListado.Size = new Size(692, 520);
            panelListado.TabIndex = 2;
            lblCantidad.AutoSize = true;
            lblCantidad.Font = new Font("Segoe UI", 10F, FontStyle.Bold, GraphicsUnit.Point);
            lblCantidad.Location = new Point(18, 18);
            lblCantidad.Name = "lblCantidad";
            lblCantidad.Size = new Size(154, 19);
            lblCantidad.TabIndex = 0;
            lblCantidad.Text = "Paquetes registrados:";
            dgvPaquetes.AllowUserToAddRows = false;
            dgvPaquetes.AllowUserToDeleteRows = false;
            dgvPaquetes.BackgroundColor = Color.White;
            dgvPaquetes.BorderStyle = BorderStyle.None;
            dgvPaquetes.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvPaquetes.Location = new Point(18, 52);
            dgvPaquetes.Name = "dgvPaquetes";
            dgvPaquetes.ReadOnly = true;
            dgvPaquetes.RowHeadersVisible = false;
            dgvPaquetes.RowTemplate.Height = 25;
            dgvPaquetes.Size = new Size(656, 450);
            dgvPaquetes.TabIndex = 1;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(230, 233, 238);
            ClientSize = new Size(1184, 701);
            Controls.Add(panelListado);
            Controls.Add(panelForm);
            Controls.Add(panelHeader);
            Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
            MinimumSize = new Size(1200, 740);
            Name = "PaqueteForm";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Registro de Paquetes";
            panelHeader.ResumeLayout(false);
            panelHeader.PerformLayout();
            panelForm.ResumeLayout(false);
            panelForm.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)nudPeso).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudAlto).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudAncho).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudLargo).EndInit();
            panelListado.ResumeLayout(false);
            panelListado.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvPaquetes).EndInit();
            ResumeLayout(false);
        }

        private Panel panelHeader;
        private Label lblTitulo;
        private Label lblSubtitulo;
        private Panel panelForm;
        private Label lblTracking;
        private TextBox txtTracking;
        private Label lblPeso;
        private NumericUpDown nudPeso;
        private Label lblAlto;
        private NumericUpDown nudAlto;
        private Label lblAncho;
        private NumericUpDown nudAncho;
        private Label lblLargo;
        private NumericUpDown nudLargo;
        private Label lblTransportista;
        private TextBox txtTransportista;
        private Label lblFechaRecepcion;
        private DateTimePicker dtpFechaRecepcion;
        private Label lblObservaciones;
        private TextBox txtObservaciones;
        private Label lblCliente;
        private TextBox txtCliente;
        private Button btnGuardar;
        private Button btnLimpiar;
        private Panel panelListado;
        private Label lblCantidad;
        private DataGridView dgvPaquetes;
    }
}
